version: "3.8"
services:
  server:
    image: server_image
    container_name: server
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ".:/app"
      - ./node_modules:/usr/app/node_modules
    # Сервис будет запущен, только после старта db
    depends_on:
     - db
  # database
  db:
    container_name: db_container
      # Имя образа. Здесь мы используем базу данных Postgres
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data