version: "3.8"
services:
  server:
    image: server_image
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 4000:5000